- name: Build APK (The Ultimate Fix)
      env:
        CI: true
        FLET_TELEMETRY_DISABLE: 1
      run: |
        # 1. Приймаємо ліцензії
        yes | flutter doctor --android-licenses
        
        # 2. ЖОРСТКО вимикаємо всю аналітику Google, яка вішає процес
        flutter config --no-analytics
        dart --disable-analytics
        
        # 3. Вимикаємо Gradle Daemon (щоб не висів у пам'яті сервера)
        mkdir -p ~/.gradle
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
        
        # 4. Запускаємо збірку
        yes | flet build apk .
